theme: jekyll-theme-midnight
joya  " github-páginas " , del grupo:  : jekyll_plugins
Título : [AppControlCasa] 
Descripción : [En esta pagina se describe un poco el contenido del funcionamiento de la applicacion y algunos datos importantes de la realización del proyecto]
Descripción :[Este proyecto se realizo para la materia de Programación Orientada a Objetos en la Universidad Autonoma de san Luis potosi]
